# This is a TOML document. Boom.

[mysql]
	dsn = "root:123456@tcp(127.0.0.1:3306)/goadmin?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(127.0.0.1:3306)/goadmin?timeout=2000ms&readTimeout=2000ms&writeTimeout=2000ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout = 3600

[web]
    port = 8890
    dir = "../resources"
    static = "static"
    template = "template/**/*"
    openTrace = false

[captcha]

[trace]
    dsn = "http://localhost:14268/api/traces"
    serviceName = "goadmin"
    proto = "http"

[bm]
    openTrace = false

[log]
    level = "info"
    debug = true
    levelSeparate = true
    stdout = true
    [log.lbj]
        dir = "./logs"
        maxSize = 128
        maxBackups = 100
        maxAge = 7
        compress = true
    [log.agent]

[redis]
    name = ""
    openTrace = false
    maxIdle = 100
    maxActive = 100
    idleTimeout = "10s"
    Addr = "127.0.0.1:6379"
    db = 0
    password = ""
    DialTimeout = "1s"
    ReadTimeout = "1s"
    WriteTimeout = "1s"
    adminSessionExpire = "8h"

[httpClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000

[Ip2Region]
    path="./ip2region.db"

[adminApi]
    url="http://127.0.0.1:9970/admin"
    aesKey="t!/NeG8~yR#pt2VG(fD0yQQMt2^p]nBo"
    aesIv="}6`9ewO_@RQ0ki|J"

[upload]
    path="./upload"