# This is a TOML document. Boom.

port = 8890

[mysql]
	dsn = "root:123456@tcp(127.0.0.1:3306)/goadmin?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Asia%2FShanghai&charset=utf8,utf8mb4"
	readDSN = ["root:123456@tcp(127.0.0.1:3306)/goadmin?timeout=2000ms&readTimeout=2000ms&writeTimeout=2000ms&parseTime=true&loc=Asia%2FShanghai&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout = 3600

[redis]
    name = ""
    openTrace = false
    maxIdle = 100
    maxActive = 100
    idleTimeout = "10s"
    Addr = "127.0.0.1:6379"
    db = 0
    password = ""
    DialTimeout = "1s"
    ReadTimeout = "1s"
    WriteTimeout = "1s"
    adminSessionExpire = "8h"

[Ip2Region]
    path="./ip2region.db"
